version: '3.8'

services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview_calendar
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs-app:
    build: .
    container_name: nestjs-app
    restart: always
    depends_on:
      - postgres-db
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: >
      sh -c "npx wait-on tcp:postgres-db:5432 &&
             npm run start:dev"

volumes:
  pgdata:
